spring:
  application:
    name: bookstore-api
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore-db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:  
    show-sql: true
    hibernate:
      ddl-auto: update
